[production]
coditent-prod ansible_host=34.205.255.37 ansible_user=ubuntu

[staging]
# coditent-staging ansible_host=1.2.3.4 ansible_user=ubuntu

[local]
localhost ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
